[api]
# Enable CORS for Edge Functions
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false  # Webhooks come from Stripe, not authenticated users